import type { Route } from "./+types/home";
import { LandingPage } from "../components/LandingPage";
import type { Project } from "../components/ProjectsSection";

export async function clientLoader(): Promise<{ projects: Project[] }> {
  // In SPA mode (ssr: false), clientLoader runs in the browser.
  // public/projects.json is generated by the GitHub Action at build time
  // and served as a static asset. Falls back to empty array gracefully.
  try {
    const res = await fetch("/projects.json");
    if (!res.ok) return { projects: [] };
    const data: unknown = await res.json();
    if (!Array.isArray(data)) return { projects: [] };
    return { projects: data as Project[] };
  } catch {
    return { projects: [] };
  }
}

// Ensure the component waits for clientLoader before first render
clientLoader.hydrate = true as const;

export function meta(): ReturnType<Route.MetaFunction> {
  return [
    { title: "Andika Dinata" },
    {
      name: "description",
      content: "Software engineer and CS student at Sumatera Institute of Technology. Interested in theoretical computer science and cybersecurity.",
    },
  ];
}

export default function Home({ loaderData }: Route.ComponentProps) {
  return <LandingPage projects={loaderData.projects} />;
}
